dialect = "us"
timezone = "local"

auto_sync = true
update_check = false
sync_address = "http://ejri.local:8888"
sync_frequency = "10m"

filter_mode_shell_up_key_binding = "session"

workspaces = true

enter_accept = true

keymap_mode = "vim-insert"

history_filter = [
  "^cd ",
  "^wd ",
  "^ls$",
  "^exit$",
]

[stats]
ignored_commands = [
  "cd",
  "wd"
]

[keys]
scroll_exits = true

[sync]
records = true

[dotfiles]
enabled = false
