dialect = "us"
timezone = "local"

auto_sync = true
update_check = false
sync_address = "http://ejri.home.arpa:8888"
sync_frequency = "10m"

style = "full"
inline_height = 0

filter_mode_shell_up_key_binding = "session"

workspaces = true

enter_accept = true

keymap_mode = "vim-insert"
# Can use this again with Wezterm instead of Windows Terminal
keymap_cursor = { emacs = "steady-block", vim_insert = "steady-bar", vim_normal = "steady-block" }

history_filter = [
  "^cd ",
  "^wd ",
  "^ls$",
  "^exit$",
]

[stats]
ignored_commands = [
  "cd",
  "wd"
]

[keys]
scroll_exits = true

[sync]
records = true

[dotfiles]
enabled = false
