export EDITOR=vim

if [[ $- == *i* ]]; then
	PROMPT_DIRTRIM=3
	PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Don't put username in title
	PROMPT_COMMAND='printf "\033]0;%s:%s\007" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'

# Solid block cursor
	echo -en '\e[2 q'
	bind 'set completion-ignore-case on'

	source ~/.config/bash/bash_aliases

	function cd {
		builtin cd "$@" && ls
	}

	source ~/.ejrconfig/bash/wd-bash.sh
fi

