app_launch_prefix = "uwsm app -- "
ignore_mouse = true
disabled = ["ai", "windows", "translation"]

[builtins.runner]
prefix = ":"
switcher_only = true

[[builtins.websearch.entries]]
name = "Kagi"
url = "https://kagi.com/search?q=%TERM%"
